%% Setup Drone
m = 0.2
I = [[0.1,0,0];[0,0.1,0];[0,0,0.08]]

% sample time
ts = 0.010

% Initial States (Initial XYZ is generated by XYZsignal script)
Euler_0 = [0;0;0]

% XYZ_0 should not be [0;0;0] because the initial target point is set to
% [0;0;0]
XYZ_0 = [0.2;0.1;0]
body_rate_0 = [0.1;0.3;0]

% Set surround rate (if 0: follow mode; if 0.5: surround mode)
surround_rate = 0.5

% Environment
g = [1;1.5;-7]
